server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/elegant_reviews_db
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: ReviewsService
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB